### ISSUE TITLE
Add environment variables for clarity

### ISSUE THREAD

**Issue by FabPei** [Iakobs/godot-play-game-services#1]
Hi,
basically the title. I got an error that the SDK wasn't found. Turns out, no environment variables were added when i installed android studio. Perhaps, you could add "Be sure to have "ANDROID_HOME" set up as an environment variable." in the instructions. Great work otherwise!

**Comment by Iakobs** [comment]
Hi @FabPei that's a great suggestion! I will add that to the docs asap.

Thanks for your kind words, too! It's the plugin working fine for you? I would love to know if everything is working as expected or not, please don't hesitate to ask any questions or make more suggestions!

**Comment by FabPei** [comment]
I am actually quite confused by setting up the demo screne. It got it to build to apk and start on my phone, but nothing really happens when using the button. I guess the Play Services thing should show up?

**Comment by Iakobs** [comment]
Hi @FabPei !

First of all, I'm assuming that you have created an app in your Google dev console and you put your game id in the configuration inside the new dock at the bottom of the godot engine.

When you open the app, does it show a small pop-up at the top indicating that you are logged in to your play games account? If not, make sure you download the play games app and you're logged in.

If you are logged in and nothing pops up, assuming the initial configuration I explained in the 1st paragraph, then you should look into the logs with adb (it's easier from android audio).

I'm planning on adding a troubleshooting section to the docs, but first I want to finish the plugin functionality.

**Comment by FabPei** [comment]
Hi, 

Yes i set up everything in Play Console. But only recently, so maybe the my service ID is simply not "online" yet.

I debug via USB and i get no error messages, so maybe i should just wait a couple of hours ;)

**Comment by FabPei** [comment]
Okay, i redownloaded the repository. Here are my steps:

Use gradlew assemble via cmd.
Import the demo project in Godot.
Enter own app id in the tab at the bottom of Godot.
Check if the plugin is enabled in Project Settings.
Press play: "No plugin found." in Output, weird.
Installed Android Template. Click on Export to Android.
Added random package name. Filled real keystore and password.
Enabled Gradle build.
Export apk.
New error message: "Icon.png" not found, added random icon.png to project files.
Install apk, button work, but do not show any Gplay Services.
Connect via USB to phone, deploy via USB.
No error messages >:I

I am quite unsure why the singleton is not found, although its enabled.

**Comment by Iakobs** [comment]
Hey @FabPei I'm glad it worked! I was reading the message and I saw that using a random package was the problem. I will try to make the documentation more explicit about this part.

I'm closing the issue for now, please reach out if you need something else!
