### ISSUE TITLE
Proposal: Access to Server Auth Token

### ISSUE THREAD

**Issue by AndrewSumsion** [Iakobs/godot-play-game-services#10]
A very useful feature that is exposed by the GamesSignInClient API is the ability to get a server auth token that can be used to verify a user.

See more here: https://developers.google.com/games/services/android/offline-access#get_the_server_auth_code

It doesn't look like this feature is present, but it should be pretty simple to add to SignInProxy.kt. You would just need to modify the code from the documentation to emit a signal when it gets the server auth token.

**Comment by Iakobs** [comment]
Hi @AndrewSumsion sorry for the late reply! I've been participating in a game jam and this week has been crazy :)

That is a very good proposal, I will put it first in my priorities list, for what you say is true; the implementation should be easy. I think this might be implemented during the next week.

Thanks again for your interest in the project and your help making proposals!

**Comment by Iakobs** [comment]
Hi again @AndrewSumsion I just released [version 1.3.0 ](https://github.com/Iakobs/godot-play-game-services/releases/tag/v1.3.0) with the method for requesting server side access.

It would be great if you could give it a try and check everything works for you! thanks again!

**Comment by Iakobs** [comment]
Hi @AndrewSumsion I'm closing this issue now, if that's ok. Please let me know if you need anything else!
