### ISSUE TITLE
Many class names clash with commonly used names

### ISSUE THREAD

**Issue by bryanmylee** [Iakobs/godot-play-game-services#11]
It would be great if all the classes used in this plugin had a specific prefix, like `PGS` or something. There are a lot of names used that conflict with my existing code, e.g. `Player`.

Although, it's not too much of an issue as I can just modify the files directly.

**Comment by Iakobs** [comment]
Hi @bryanmylee thanks a lot for your suggestion, that's very true indeed! I will change them as soon as I can.

**Comment by bryanmylee** [comment]
My bad, seems like Godot was just confused about some of the conflicting class names. A few restarts seem to solve the conflict with the nested class definitions!
