### ISSUE TITLE
Missing support for Events API

### ISSUE THREAD

**Issue by godfryd** [Iakobs/godot-play-game-services#12]
this is missing: https://developers.google.com/games/services/android/events

**Comment by Iakobs** [comment]
Hi @godfryd thanks for your interest, I'm aware of this and I have plans to add the events API to the plugin in the near future, I'll keep you posted.

**Comment by Iakobs** [comment]
Hi @godfryd the events functionalities have been added to the plugin. Thanks for your patience!
