### ISSUE TITLE
Game ID length is limited to 12 chars while it can be bigger

### ISSUE THREAD

**Issue by godfryd** [Iakobs/godot-play-game-services#13]
in my case, this is 13 chars

**Comment by Iakobs** [comment]
hi @godfryd my bad! I will change that ASAP, in the meantime you can just put your game id manually in the corresponding strings.xml file inside the `/android/build` android template

**Comment by Iakobs** [comment]
Hi @godfryd I've pushed the change, increasing from 12 to 20 characters.

I haven't made a release yet (I want to include some other changes before making a new release), but you can try it out compiling the plugin manually from [this commit](b726e240fc445ba6014cc155815ccd32759883f3).

Thanks for your help!

**Comment by Iakobs** [comment]
Hi @godfryd I'm closing the issue. Let me know if you need something else. Thanks!
