### ISSUE TITLE
Lots of errors from the plugin just after installation

### ISSUE THREAD

**Issue by owlnewworlds** [Iakobs/godot-play-game-services#14]
Hello !

I'm using Godot 4.2.1 and I've just installed your plugin for Godot 4.2.
But just after the installation is completed, the panel in Godot Editor is showing a lot of errors, mostly a lot of parse errors from the gd files inside the plugin.

Is there anything I missed, or a problem right now?
Thanks for your help!

Owl

![Capture d'écran 2024-02-15 191141](https://github.com/Iakobs/godot-play-game-services/assets/156072785/c23d3c40-95c3-4eac-bc56-56ef69f91198)

**Comment by Iakobs** [comment]
Hi @owlnewworlds

Thanks for reaching out! I've seen this happens the first time you load the plugin, when you reopen the project, is it ok?

I still have to figure out why these errors appear on first load, though.

**Comment by owlnewworlds** [comment]
Hello @Iakobs ! Thanks for your quick answer.

You're right, when I reload the project, the errors don't reappear again.

Just so you know, I also had new errors when I added the Game ID through the editor plugin window but, same as first load, these errors don't seem to appear again on next reload of the project.

For now, I'm trying to continue on the config and see if the plugin does work despite the errors. But since you seem to be aware of this first time issue, I suppose it will be fine ^^

**Comment by Iakobs** [comment]
No worries! it's actually very annoying, I don't understand where those pesky errors come from! I should put a warning in the readme 🤔

About the game id, do you remember the words? I don't remember any in that part

**Comment by owlnewworlds** [comment]
Yes, here is a screenshot of the errors after submitting the Game ID! Very weird errors, I didn't understand them since the gd scripts extends Node.

![Capture d'écran 2024-02-15 192034](https://github.com/Iakobs/godot-play-game-services/assets/156072785/0aa21eca-63bb-4d79-bcbd-06ba69bbc4ba)

**Comment by Iakobs** [comment]
Hi @owlnewworlds I changed the load order of the autoloads, disabled the plugin by default and updated the readme of the demo project to warn about the errors. They are still there, I can't figure out why, so that's the best I can do. I will close this issue now :)
