### ISSUE TITLE
Where i must put ID leaderboard?

### ISSUE THREAD

**Issue by ZiiGame** [Iakobs/godot-play-game-services#15]
Hi i am newq in godot.
Where i can put ID Leaderboard from my google cloud to your plugin?
Thx for future answer.

**Comment by Iakobs** [comment]
Hi @ZiiGame 

You don't have to put your leaderboards or achievements ids in any specific place. You have some methods in the plugin where you can send the leaderboard ids to get or submit scores, to show a specific leaderboard, etc. These methods are in the [LeaderboardClient](https://github.com/Iakobs/godot-play-game-services/blob/main/plugin/export_scripts_template/autoloads/leaderboards_client.gd) of the godot plugin. The same logic applies for achievements, with relevant methods in the [AchievementsClient](https://github.com/Iakobs/godot-play-game-services/blob/main/plugin/export_scripts_template/autoloads/achievements_client.gd).

You have some examples of its usage in the demo project, [here](https://github.com/Iakobs/godot-play-game-services/blob/main/plugin/demo/scenes/leaderboards/LeaderboardDisplay.gd#L103) and [here](https://github.com/Iakobs/godot-play-game-services/blob/main/plugin/demo/scenes/leaderboards/LeaderboardDisplay.gd#L96).

You have some explanation on how to run the demo project and how it works in the [README](https://github.com/Iakobs/godot-play-game-services/tree/main/plugin/demo) of the demo project itself. You can open that folder from Godot and follow the steps described there and you should be able to run the demo project.

Please let me know if you need any more help, hope the plugin works for you!

**Comment by ZiiGame** [comment]
Hi @Iakobs 

If I understand correctly so instead of this

func _load_player_score() -> void:
	LeaderboardsClient.load_player_score(
		leaderboard.leaderboard_id,
		LeaderboardsClient.TimeSpan.TIME_SPAN_ALL_TIME,
		LeaderboardsClient.Collection.COLLECTION_PUBLIC
	)
	
	
I use my exaplcode as vrvnevnei5vv

So the result will be 

func _load_player_score() -> void:
	LeaderboardsClient.load_player_score(
		leaderboard.**vrvnevnei5vv**,
		LeaderboardsClient.TimeSpan.TIME_SPAN_ALL_TIME,
		LeaderboardsClient.Collection.COLLECTION_PUBLIC
	)
	
Sorry to bother you and delay you. I just tried to find it on youtube and I was looking at your demo project and tried reverse engineering. But I didn't see the leaderboard ID from google cloud anywhere, and when I tried to insert it after leaderboard_id, I kept getting an error.
I'm a complete beginner, so I'm mostly learning by trial and error.
Everywhere on youtube we only saw videos on the 3.5 version and there they used a constant definition for the id of each leaderboard created in the google cloud.
Thank you for your patience.

**Comment by ZiiGame** [comment]
![image](https://github.com/Iakobs/godot-play-game-services/assets/152533248/b32fa6d2-4692-423e-be26-ff8c03b9456c)

**Comment by ZiiGame** [comment]
![image](https://github.com/Iakobs/godot-play-game-services/assets/152533248/eb628889-eed7-4b51-a373-f2db61cc48eb)

**Comment by Iakobs** [comment]
Hi! I'm happy to help, don't worry about asking :) I try to explain as simple as possible, but don't be afraid to ask again if you don't understand something.

In the demo project the leaderboard id is loaded from google directly, connecting to the `all_leaderboards_loaded` signal, [here](https://github.com/Iakobs/godot-play-game-services/blob/main/plugin/demo/scenes/leaderboards/Leaderboards.gd#L13). Then that leaderboard information is stored in the LeaderboardDisplay scene, which uses the leaderboard id to call the method you are referring to. You can do that or either use your constants as you saw on youtube.

**Comment by ZiiGame** [comment]
Bro it works. Thank you very much.
Now I just have to figure out how to put player points into that leaderboard and I'll be done. Thank you very much.

Do you happen to know any plugin for storing data on firebase? I have paired firebase only for analytical data, but I haven't seen anywhere a functional connection to android that I will create in firebase storage and save and upload data there when I just log in to google service via your plugin. If you don't know, then don't bother me just in case you don't know.
Once again, thank you very much for the explanation.

**Comment by Iakobs** [comment]
Hey! I'm so happy it works! I don't know about any plugin for firebase, though. Hope you can find what you're looking for
