### ISSUE TITLE
Error 7 its a problem ?

### ISSUE THREAD

**Issue by ZiiGame** [Iakobs/godot-play-game-services#16]
Hi i have this error and i dont found in close topics similar problem.
Its a problem or i can let it be ?

Error loading configuration for Game Services! Error: 7

![image](https://github.com/Iakobs/godot-play-game-services/assets/152533248/1f7eb996-c354-47fa-9654-fe4f82072847)

**Comment by Iakobs** [comment]
Hi @ZiiGame 

it's hard to know only with that, does logcat say something else? How can I try to reproduce the error (ie. steps you did to reach that error)

**Comment by ZiiGame** [comment]
hi @Iakobs 

I remove from my project from GODOT in addons your plugin. Before i click off in project settings plugin and after delete from folder. Save and quit godot. After i unzip 1,4 version the same version and put on folder addon back. I start godot and i see this i click on project settings plugin on and global script check for ON. I turn off and on GODOT and same this error. I delete project folder and from USB upload backup but in backup its too. I think there been all time but i acknowledge this error now and past time i dont care because i working on some else.

**Comment by ZiiGame** [comment]
OK i found error :DDDD I forgot put again ID from google service.
