### ISSUE TITLE
More snapshot functionality

### ISSUE THREAD

**Issue by 3prockent** [Iakobs/godot-play-game-services#17]
Hi!

Are there any plans to create methods:
1) getting a list of all Snapshots
2) Checking whether a snapshot exists at a given Id (This method would be appropriate, because if load_snapshot with a non-existent Id, the application simply closes. It would be convenient if load_snapshot in this case returned an error or at least null, but did not kill the application)
3)Removing Snapshot?

1 and 3 would be very useful if the user does not want to use the standard show_snapshots pop-up window, but implement his own custom one, as I did in this case. Now I use solutions that work, but are crutches

**Comment by Iakobs** [comment]
Hi @3prockent thanks for your interest and your questions.

I will note this down and them to the backlog, I also think they are good ideas to add to the plugin. I'll keep you posted!

**Comment by Iakobs** [comment]
Hi @3prockent and @KeiMuriKoe 

All of these have been added in the [latest release](https://github.com/Iakobs/godot-play-game-services/releases/tag/v1.6.0).

Please, let me know if everything works for you. In the meantime, I'm closing this issue.

Thanks a lot for your patience!!

**Comment by KeiMuriKoe** [comment]
> Hi @3prockent and @KeiMuriKoe
> 
> All of these have been added in the [latest release](https://github.com/Iakobs/godot-play-game-services/releases/tag/v1.6.0).
> 
> Please, let me know if everything works for you. In the meantime, I'm closing this issue.
> 
> Thanks a lot for your patience!!

Bro, no way! Thank you so much for your work, I'll definitely provide feedback.

**Comment by KeiMuriKoe** [comment]
I apologize for the delay in my response, I wanted to be absolutely sure that everything was working as expected. Everything is working wonderfully, thank you so much! This functionality has helped me to remove a lot of unnecessary code. Thank you!

**Comment by Iakobs** [comment]
Hey @KeiMuriKoe I'm so happy the plugin is helping you! Let me know if there's anything else!
