### ISSUE TITLE
Plugin not found

### ISSUE THREAD

**Issue by isthargames** [Iakobs/godot-play-game-services#24]
Hello! How are you? I'm having some trouble setting up a plugin in my Android game. I've set up my credentials and created my app in Google Play Console. Also, I've activated the plugin and autoload, but when I run the game on my Android device, it just keeps running without doing anything. I'm not sure what further steps to take or if there's something I'm not understanding correctly. Could you help me?
![1](https://github.com/Iakobs/godot-play-game-services/assets/149918776/e77c4ad9-8798-411e-9faf-75626e712240)
![2](https://github.com/Iakobs/godot-play-game-services/assets/149918776/df89f401-fa96-47c6-bccd-450913478165)

**Comment by Iakobs** [comment]
Hi @isthargames I'm well thanks! and you?

Thanks for your interest in the plugin! A part from setting everything app in google play and activating the plugin, did you actually use any of the methods in the plugin? In the demo project there's a [README](https://github.com/Iakobs/godot-play-game-services/tree/main/plugin/demo) with some explanation on how to setup authentication, calling for leaderboards, etc.

If you already have done that, is there anything useful in the logs in logcat? I usually use this regex in logcat to better filter the logs: `package:com.jacobibanez.godot.test.game package:com.google.android.gms`

Please let me know what else you have tried, let's see if we can get your tamagotchi to work :)

**Comment by Iakobs** [comment]
Hi @isthargames I'm closing the issue. Please, let me know if you have any other questions :)
