### ISSUE TITLE
Plugin not working in Google play.

### ISSUE THREAD

**Issue by bascimehmet** [Iakobs/godot-play-game-services#27]
i send the game in my phone with adb and plugin iş working excellent. But i publish game in Google play console and i downlanding game with Google play app. then plugin is not working.  I seeing only signin loading icon. Leaderboards button is not wokring. 

Maybe proguard code standart is importent, maybe other problem. What do you think about this.

**Comment by Iakobs** [comment]
Hi! Have you checked [this](https://github.com/Iakobs/godot-play-game-services?tab=readme-ov-file#solving-the-problem)? You need to add a new Credential for the Play Store certificate once you publish the game.

Please, let me know if this helped!

**Comment by bascimehmet** [comment]
After doing what you said, I signin PGS and saw the leaderboard. But unfortunately, the scores obtained in the game are not recorded. I just installed the application via adb from my computer and recorded the score without any problems. However, the score data recorded in the application downloaded from Google Play is not recorded in the leaderboard.  thanks for your answer
