### ISSUE TITLE
The display is "Score" instead of duration

### ISSUE THREAD

**Issue by lazyvainglory** [Iakobs/godot-play-game-services#30]
I don’t really know if this issue is specific to this addon, but I thought I’d ask anyway. I set up my leaderboard to accept duration, yet it displays ‘Score’ instead of duration.

![image](https://github.com/Iakobs/godot-play-game-services/assets/45304248/e3a29e0b-24c1-4844-a319-e0747de470e3)

![image](https://github.com/Iakobs/godot-play-game-services/assets/45304248/c69128fb-a80b-4025-a898-d95fdaf75042)

Also, I would like to ask if it’s possible to display an error using Play Games Services popup/notification. I’m wondering if I could use it to inform the user that the score did not submit due to a lack of internet connection.

![image](https://github.com/Iakobs/godot-play-game-services/assets/45304248/efdf2a94-cbf0-45ba-b1b5-8dff18000bb5)

Lastly, thank you so much for this addon. It was really helpful. I’ve been trying to implement Play Games Services for days now, and this addon truly saved me. Thank you so much!

**Comment by Iakobs** [comment]
Hi @lazyvainglory thanks a lot for your kind words! I'm very happy that the plugin is serving you well!

About your first question, I'm afraid this is all google related. The display of the leaderboard is controlled in their end. It is weird, though, that it doesn't display correctly. Have you published the changes in the Google Play Games section of your app?

About the notifications, I think it's an interesting idea. I will definitely look into that when I have some time!

Thanks again for reaching out!

**Comment by lazyvainglory** [comment]
Thanks for confirming my suspicion, and don’t worry about it. I’ll figure it out eventually. LOL! Thanks again, and consider this case closed.
