### ISSUE TITLE
Migration to the official godot organization for hosting SDK

### ISSUE THREAD

**Issue by DeanLemans** [Iakobs/godot-play-game-services#34]
Could you maby consider migrating to the [official centralized GitHub organization for hosting SDK integrations](https://github.com/godot-sdk-integrations#list-of-godot-sdk-integrations)?

There is a whole [blog post](https://godotengine.org/article/godot-sdk-integrations/) about this on thr godot site.

**Comment by Iakobs** [comment]
Hi @DeanLemans thanks a lot for your interest and considering my plugin worthy to be there! It happens to be that I'm already in conversations with the Godot Foundation to migrate it, so that's indeed the plan!
