### ISSUE TITLE
Question regarding snapshot conflict

### ISSUE THREAD

**Issue by RProduction** [Iakobs/godot-play-game-services#35]
Hello, I am currently using this plugin for my game. Is there any direction or sample code for resolving snapshot conflict?
I am currently having a problem that my game save data seem not loading well after some change, or deleting application data. I need to restart the app for it to load well, but there is no way I am going to let this problem slide.

I need your help regarding this matter.

**Comment by Iakobs** [comment]
Hi! The plugin is just an interface between the Google API and Godot, so at the end of the day you should be fine following [Google's documentation](https://developers.google.com/games/services) on it, that's what I used to develop the plugin.

For save games specifically you can take a look [here](https://developers.google.com/games/services/common/concepts/savedgames), but the docs are quite scarce. This project has a demo app [here](https://github.com/Iakobs/godot-play-game-services/tree/main/plugin/demo) that you can open and Godot. In theory, if you provide a Game Id of your own, you should be able to run the demo app in an android device and test it there, but I've only tried with my own Game Id, not others.

If you do find a problem in the plugin implementation please let me know, and I'll fix it ASAP, but as mentioned and providing that I didn't mess anything, it's just a bypass between Google and Godot! 😅

**Comment by RProduction** [comment]
Thank you for answering.
What I mean is snapshot_conflict_emitted just provide the snapshot data without public function to resolve the conflict. Meanwhile android sdk of google play games give function to resolve the conflict.

Unity google game sdk also have option to resolve conflict manually or automatically.

I can't even choose what snapshot to be loaded or saved from snapshot_conflict_emitted signal.

**Comment by Iakobs** [comment]
Hi! If I understand it correctly, you need to know what action triggered the `conflict_emitted` signal, either the load or the save methods? I can add a field in the `SnapshotConflict` object coming in that signal, to indicate the original caller, something like a string with "Save" or "Load", that would be enough for you?

I remember trying to implement the manual flow for resolving conflicts, but I think there was a problem with object types conversion between Java and GDScript. I can try again, too, but if adding the `origin` field to the `SnapshotConflict` solves the problem for now, I can quickly try that. What do you think?

**Comment by Iakobs** [comment]
Can you try this version of the plugin? I added a `origin` field to the `SnapshotConflinct` class in the `SnapshotsClient` autoload, so now you will know which method originated the conflict. The possible values are either `LOAD` or `SAVE`.

If this works, let me know and I will push the new version to the repo.

[addons.zip](https://github.com/user-attachments/files/17282403/addons.zip)

**Comment by RProduction** [comment]
Okay, I will try it

**Comment by RProduction** [comment]
Hey, it works. It give me "SAVE" and "LOAD" string for each operation in origin.

**Comment by Iakobs** [comment]
Nice! In the meantime, what's the manual flow to solve conflicts in other sdks? do you have any examples?

**Comment by Iakobs** [comment]
I don't understand either how to do conflict resolution. What I understand from Google's docs is that the designer of the game has to decide depending on every case. I guess there's no correct answer to the question.

**Comment by Iakobs** [comment]
Hi @RProduction I'm closing the issue for now, but please feel free to ask any other questions!
