### ISSUE TITLE
Unable to enable the plugin

### ISSUE THREAD

**Issue by Draethos** [Iakobs/godot-play-game-services#4]
I downloaded the plugin and put it in the demo project to try it out as I have no idea how to work with java so I needed the demo, but it keeps giving me this error "res://addons/addons/GodotPlayGameServices/export_plugin.gd’. This might be due to a code error in that script.
Disabling the addon at ‘res://addons/addons/GodotPlayGameServices/plugin.cfg’ to prevent further errors."

**Comment by Iakobs** [comment]
Hi @Draethos !

It does that the first time you open the project, I'm still not sure why. It is usually solved by reloading the project in Godot.

If the problem persists, please try to attach a screenshot of the godot logs.

Just take into account that to test the plugin you will need to configure it with your App Id (more information in the README of the repository), and you also will need to run the game in an android device (real or emulated), which implies installing an android build template:

![imagen](https://github.com/Iakobs/godot-play-game-services/assets/10604600/08dbf6ec-b587-4d1d-8129-97f54ff3f02f)

And then running the game like this:

![imagen](https://github.com/Iakobs/godot-play-game-services/assets/10604600/03e1219b-bee3-457f-8fb3-41bcd47dc76c)

**Comment by Draethos** [comment]
I reloaded the project and it sent the same thing

**Comment by Iakobs** [comment]
Can you attach a screenshot of the output of the logs in the editor? It's difficult to help without more information :)

**Comment by Draethos** [comment]
Which logs exactly? Because all I'm getting is the 
"res://addons/addons/GodotPlayGameServices/export_plugin.gd’. This might be due to a code error in that script.
Disabling the addon at ‘res://addons/addons/GodotPlayGameServices/plugin.cfg’ to prevent further errors."

**Comment by Iakobs** [comment]
ok, that's weird. I was refering to the output in the editor:

![imagen](https://github.com/Iakobs/godot-play-game-services/assets/10604600/ea13d4f5-a77e-418b-8ba6-80c01305abca)

But if that's the only thing you get, then that's weird. When and where do you see this error? Can you explain to me the steps you take from the beginning, so I can try to reproduce the error?

Thanks a lot!

**Comment by Draethos** [comment]
Yes of course. So I took the addons.zip that you can download and put it into the demo folder's addons folder. I went into Godot and then Project --> Project Settings --> Plugins --> Enable. When I try to enable the plugin it sends me this.
![Screenshot (739)](https://github.com/Iakobs/godot-play-game-services/assets/155439047/e85d1234-8a7b-4ba1-aa22-03d1d5bafda4)

**Comment by Iakobs** [comment]
The first thing I can see is that you are not using version 4.2 of Godot. This plugin is only for Godot 4.2 or higher (well, 4.2 is the highest right now 😛 ), could you try installing Godot 4.2 and trying there?

**Comment by Draethos** [comment]
Yea ill try. Itll take me some time cause ive got bad internet.

**Comment by Iakobs** [comment]
no worries! just let me know if that solves your problem, no hurries!!

**Comment by Draethos** [comment]
It did solve the problem. Thank you so much mate. Have a great new year

**Comment by Iakobs** [comment]
yay!! I'm glad it works now! Have a great year you too!
