### ISSUE TITLE
crashing upon calling show_leaderboard(leaderboard_id: String)

### ISSUE THREAD

**Issue by mrbut1995** [Iakobs/godot-play-game-services#5]
When i called LeaderboardsClient.show_leaderboard(leaderboard_id: String), its crash and give a warning:
> Invalid call. Nonexistent function 'showAllLeaderboards' in base 'JNISingleton'.

**Comment by Iakobs** [comment]
Hi @mrbut1995 

You found a bug, my friend! thanks a lot! I will be fixing it as soon as possible! Thanks again for letting me know.

**Comment by Iakobs** [comment]
Hi again @mrbut1995 you have a new release with the bug fixed! thanks again!
