### ISSUE TITLE
I can't export the game anymore

### ISSUE THREAD

**Issue by Draethos** [Iakobs/godot-play-game-services#6]
So I just finished implementing a test to try out the signing in and saving, I try to export and I get this message in the output"Could not create child process: "E:\Robin\Applications\Godot\#### \android\build\gradlew.bat" clean bundleRelease -p "E:/Robin/Applications/Godot/######/android/build" "-Pexport_package_name=#######" "-Pexport_version_code=52" "-Pexport_version_name=0.2" "-Pexport_version_min_sdk=24" "-Pexport_version_target_sdk=34" "-Pexport_enabled_abis=armeabi-v7a|arm64-v8a|x86|x86_64" "-Pplugins_local_binaries=E:/Robin/Applications/Godot/####android/plugins/GodotGooglePlayBilling.1.2.0.release.aar|E:/Robin/Applications/Godot/#######/addons/GodotPlayGameServices/bin/release/GodotPlayGameServices-release.aar"

I also get "Error loading configuration for Game Services! Error: 7" every time I open the Godot project

**Comment by Iakobs** [comment]
Hi @Draethos 

when you say you get the error in the ouput when you try to export, I'm understanding the android export, right? Have you tried running the game in an emulator or a real device through USB, instead of exporting the .aab or .apk package? Just to make sure that running in an emulator/real device has the same problem or not.

About the Error: 7 that you mention, I don't know what's that, but it looks like a problem in your configuration of the Google Play Games Services for your App.

**Comment by Draethos** [comment]
Ok so for both exporting it as .aab or .apk and using remote debugging, it gives me the problem. The error 7, idk what that is either, but we are gonna try uninstalling godot and reinstalling cause its been having problems such as never fully closing and being just a general piece of shit.

**Comment by Iakobs** [comment]
Ok, let me know if reinstalling godot works

**Comment by Draethos** [comment]
reinstalling godot did not solve the issues i am still getting error 7

**Comment by Iakobs** [comment]
Hi, so you are not getting the other error now? the "could not create child process"?

About the other error, check if you have your Google Play Games Services configuration published here:

![imagen](https://github.com/Iakobs/godot-play-game-services/assets/10604600/f7ba82c9-eddc-4191-9d1e-3d4249e4f303)

I often forgot about publishing them.

Also, a part from this error 7 when you open the project, can you signin to your Games Services account when you run the game?

**Comment by Draethos** [comment]
Ok sorry I worded my sentence wrong, I'm having BOTH issues, and the error 7 is happening every time i turn on the project or turn off then on the plugin.

**Comment by Draethos** [comment]
So i found out a minute ago, that for some reason i dont have a gradlew.bat in my android/build folder, got any ideas why that might be?

**Comment by Iakobs** [comment]
ah, ok so it seems a problem with the Android Build Template. Try completely removing the `android/build` folder of your godot project and reinstalling the android template. Make sure your template is for Godot 4.2 in the `Editor > Manage Export Templates...` menu:

![imagen](https://github.com/Iakobs/godot-play-game-services/assets/10604600/e8cbb4ef-0d08-473c-a95b-34a4dfa0a401)
![imagen](https://github.com/Iakobs/godot-play-game-services/assets/10604600/94cef1cd-3ffe-4672-b804-01d6c07b6269)

**Comment by Draethos** [comment]
Ok so I fixed both problems which might help someone later, so if u get the "Could not create child process: "E:\Robin\Applications\Godot#### \android\build\gradlew.bat" clean bundleRelease -p "E:/Robin/Applications/Godot/######/android/build" "-Pexport_package_name=#######" "-Pexport_version_code=52" "-Pexport_version_name=0.2" "-Pexport_version_min_sdk=24" "-Pexport_version_target_sdk=34" "-Pexport_enabled_abis=armeabi-v7a|arm64-v8a|x86|x86_64" "-Pplugins_local_binaries=E:/Robin/Applications/Godot/####android/plugins/GodotGooglePlayBilling.1.2.0.release.aar|E:/Robin/Applications/Godot/#######/addons/GodotPlayGameServices/bin/release/GodotPlayGameServices-release.aar" message
and the error 7, that means ure gradlew.bat is for some reason NOT installed wwith the android build template. Thank you man for trying to help me and sorry i bothered you. Hope you have a great weekend.

**Comment by Iakobs** [comment]
no worries at all man! this is very helpful and I will add the case to the troubleshooting section of the documentation! glad it works now!!
