### ISSUE TITLE
Question: How to sign out from google play?

### ISSUE THREAD

**Issue by Mefistosss** [Iakobs/godot-play-game-services#8]
If the user wants sign out from google play how can i do it?

**Comment by Iakobs** [comment]
Hi @Mefistosss , thanks for your question!

As far as I know, I'm afraid that's not an option provided by the Google API.

I would suggest implement this manually by yourself, by putting everything related with play games services behind a toggle.

In sorry I can't help you more with this.

Please let me know if there's something else I can help you with. In the meantime I will close this issue, but you can still comment on it.

**Comment by Mefistosss** [comment]
Hi @Iakobs thank you for your answer
